### PR TITLE
Add CODEOWNERS

### PR DESCRIPTION
**Pull request by ananzh**
### Issues Resolved
https://github.com/opensearch-project/opensearch-catalog/issues/9

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by seanneumann** [comment]
I think we need to rebaseline maintainers for this since ownership has transitioned to folks working on core dashboards repo.

**Review by khushbr — APPROVED** [review]

**Comment by ananzh** [comment]
@gaiksaya  could you help us to double check the permissions? If they are not correct, pls help to update them because we don't have admin permission. thx.

**Comment by ananzh** [comment]
@gaiksaya Thanks for helping. I will check with @khushbr and make updates.

**Comment by seanneumann** [comment]
@dbbaughe should be moved to Emeritus.

**Comment by ananzh** [comment]
> Hi @ananzh The codeowners file in this repo in invalid. Please check the members as well. I believe `dbbaughe` is not affiliated to Amazon anymore.

Here is the update PR: https://github.com/opensearch-project/opensearch-catalog/pull/12

**Pull request merged**
